config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:'teams#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pokemons, only: [:new, :create, :destroy]
  resources :teams
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  belongs_to :team
  validate :limit_pokemon

  def limit_pokemon
    errors.add(:base, "limite maximo de 6 pokemos") if team.full_member?
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :authenticate_user!, except: :show

  def new
    @pokemons = Pokemon::Api.pokemons
  end

  def show
    @pokemon = Pokemon.find(params[:id])
  end

  def create
    team = Team.find(params[:team_id])
    return redirect_to team_path(params[:team_id]), alert: 'Time já possui 6 pokemons' if team.full_member?
    errors = []
    params[:names].each do |name|
      pokemon = Pokemon::Api.pokemon(name)
      species = pokemon['types'].map{|x| x['type']['name'] }.join(', ')
      item = Pokemon.create(
        name: pokemon['name'],
        species: species, 
        sprite: pokemon['sprites']['other']['official-artwork']['front_default'],
        team_id: params[:team_id]
      )
      errors << { name: name, errors: item.errors.full_messages.to_sentence } if item.errors.present?
    end
    if errors.present?
      error_message = 'Os seguintes pokemons não puderam ser criados: '
      errors.each do |error|
        error_message += "#{error[:name]} - #{error[:errors]} | "
      end
      return redirect_to team_path(params[:team_id]), alert: error_message
    end
    redirect_to team_path(params[:team_id]), notice: 'Pokemon(s) criado(s) com sucesso!'
  end

  def destroy
    @pokemon = Pokemon.find(params[:id])
    team_id = @pokemon.team.id
    @pokemon.destroy
    redirect_to team_path(team_id), notice: 'Pokemon deletado com sucesso!'
  end
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/pokemons/new.html.erb
<h3 class="text-center text-primary">Selecione seus pokemons </h3>
<hr/>

<%= form_with url: pokemons_path, method: :post do |form| %>
	<table id="pokemon_id" class="table">
		<thead>
			<tr>
				<td>#</td>
				<th>Nome</th>
			</tr>
		</thead>
		<tbody>
			<% @pokemons.each do |pokemon| %>
				<tr>
						<td><input type="checkbox" name="names[]" value="<%= pokemon['name']%>"></td>
						<td><%= pokemon['name'] %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<%= form.hidden_field :team_id, value: params[:team_id] %>
	<%= form.submit 'Salvar', class: 'btn btn-primary float-end mt-2' %>
<% end %>